### ISSUE TITLE
Ranking system

### ISSUE THREAD

**Issue by qaisjp** [josefnpat/vapor#12] opened 2013-08-04 14:10 UTC
Every game can be reviewed. The reviews would either be based on a Like/Dislike system like YouTube or a starring system, I think a starring system gives people more of an idea.
So if you liked it but didn't like it, you could put 2.5 / 5 or whatever stars.

**Comment by josefnpat** [comment] 2013-08-04 14:33
Duplicate of #2

**Closed as completed by josefnpat** 2013-08-04 14:33 UTC
Labels: duplicate
